//! Milestone 3: PDB compression study for the 15-puzzle.
//!
//! Same `Report` shape as `examples/c3_pdb.rs` so results compare apples to
//! apples across puzzles. Builds (or loads) PDBs for a few partitions and
//! benchmarks them against a sample of solvable 15-puzzle positions
//! generated by random reverse-move walks of fixed depth from `GOAL`.
//!
//! Run with:
//!
//! ```text
//! cargo run --release --features puzzle15 --example m3_pdb15_study
//! ```
//!
//! Notes on scale (vs 8-puzzle):
//!
//! - The full distance table is infeasible (~5 TB), so the "exact" baseline
//!   that `c3_pdb.rs` reports is omitted here.
//! - Sample size is small (`samples = 25`, walk depth = 25) to keep runtime
//!   reasonable when iterated — Manhattan IDA\* can take hours past depth 30.
//! - "max_error_plies" is computed against a per-sample second-opinion solve
//!   with Manhattan IDA\* (admissible). For PDB heuristics, this matches the
//!   PDB result for all samples in this depth range — non-zero would
//!   indicate a correctness bug.

use std::cell::Cell;
use std::time::Instant;

use puzzle8::puzzle15::pdb::pattern::Pattern;
use puzzle8::puzzle15::pdb::{
    AdditivePdbHeuristic, MaxHeuristic, PatternDb, PdbHeuristic, ReflectedHeuristic,
};
use puzzle8::puzzle15::search::{idastar, Heuristic, ManhattanHeuristic};
use puzzle8::puzzle15::state::{Move, State, GOAL};

/// Heuristic that counts h() calls — proxy for IDA* effort.
struct CountingHeuristic<'a, H: Heuristic> {
    inner: &'a H,
    count: Cell<u64>,
}

impl<'a, H: Heuristic> CountingHeuristic<'a, H> {
    fn new(inner: &'a H) -> Self {
        Self {
            inner,
            count: Cell::new(0),
        }
    }
    fn count(&self) -> u64 {
        self.count.get()
    }
    fn reset(&self) {
        self.count.set(0);
    }
}

impl<'a, H: Heuristic> Heuristic for CountingHeuristic<'a, H> {
    fn h(&self, s: &State) -> u8 {
        self.count.set(self.count.get() + 1);
        self.inner.h(s)
    }
}

#[derive(Clone)]
struct Report {
    name: String,
    bytes_stored: usize,
    mean_solve_ns: u64,
    mean_h_calls: u64,
    max_error_plies: u8,
    samples: usize,
}

impl Report {
    fn print(&self) {
        println!(
            "  {:<40}  bytes={:>10}  mean_ns={:>11}  mean_h_calls={:>11}  max_err={}  (n={})",
            self.name,
            self.bytes_stored,
            self.mean_solve_ns,
            self.mean_h_calls,
            self.max_error_plies,
            self.samples,
        );
    }
}

fn next(s: &mut u64) -> u64 {
    *s = s.wrapping_add(0x9E3779B97F4A7C15);
    let mut z = *s;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
    z ^ (z >> 31)
}

fn random_scramble(seed: u64, depth: u32) -> State {
    let mut s = GOAL;
    let mut rng = seed;
    let mut last: Option<Move> = None;
    let mut steps = 0u32;
    while steps < depth {
        let r = next(&mut rng);
        let m = Move::ALL[(r as usize) & 3];
        if !s.legal_moves().contains(m) {
            continue;
        }
        if let Some(p) = last {
            if m == p.inverse() {
                continue;
            }
        }
        s = s.apply(m);
        last = Some(m);
        steps += 1;
    }
    s
}

fn benchmark<H: Heuristic>(
    name: &str,
    bytes_stored: usize,
    h: &H,
    samples: &[State],
    truth: &[u8],
) -> Report {
    let counting = CountingHeuristic::new(h);
    let mut total_ns: u64 = 0;
    let mut total_calls: u64 = 0;
    let mut max_err: u8 = 0;
    for (idx, s) in samples.iter().enumerate() {
        counting.reset();
        let t = Instant::now();
        let sol = idastar(s, &counting).expect("solve");
        total_ns += t.elapsed().as_nanos() as u64;
        total_calls += counting.count();
        let len = sol.len() as u8;
        let err = len.abs_diff(truth[idx]);
        if err > max_err {
            max_err = err;
        }
    }
    Report {
        name: name.to_string(),
        bytes_stored,
        mean_solve_ns: total_ns / samples.len() as u64,
        mean_h_calls: total_calls / samples.len() as u64,
        max_error_plies: max_err,
        samples: samples.len(),
    }
}

fn main() {
    const SAMPLES: usize = 25;
    const WALK_DEPTH: u32 = 25;
    const SEED_BASE: u64 = 0x00C0_FFEE_CAFE;

    // Generate samples.
    let samples: Vec<State> = (0..SAMPLES)
        .map(|k| random_scramble(SEED_BASE.wrapping_add(k as u64), WALK_DEPTH))
        .collect();

    println!(
        "Computing ground-truth distances via IDA*+Manhattan (admissible) — depth ≤ {WALK_DEPTH}."
    );
    let t = Instant::now();
    let truth: Vec<u8> = samples
        .iter()
        .map(|s| {
            idastar(s, &ManhattanHeuristic)
                .expect("manhattan solves")
                .len() as u8
        })
        .collect();
    println!(
        "Ground truth done in {:.2?}. Depths: min={} max={} mean={:.1}",
        t.elapsed(),
        truth.iter().min().unwrap(),
        truth.iter().max().unwrap(),
        truth.iter().map(|&d| d as f64).sum::<f64>() / truth.len() as f64,
    );

    println!("\n# Direction #3 (PDB) — 15-puzzle compression study\n");

    // --- Baselines ---
    let h_man = ManhattanHeuristic;
    Report {
        ..benchmark("Manhattan", 0, &h_man, &samples, &truth)
    }
    .print();

    // --- Small additive partition (4+4+4+3 covering all 15 tiles) ---
    println!("\nBuilding small PDBs (will take a few seconds each)...");
    let t = Instant::now();
    let p_a = PatternDb::build(Pattern::new(&[1, 2, 3, 4]));
    let p_b = PatternDb::build(Pattern::new(&[5, 6, 7, 8]));
    let p_c = PatternDb::build(Pattern::new(&[9, 10, 11, 12]));
    let p_d = PatternDb::build(Pattern::new(&[13, 14, 15]));
    println!("Built 4+4+4+3 partition in {:.2?}", t.elapsed());

    let bytes_4443 =
        p_a.bytes_stored() + p_b.bytes_stored() + p_c.bytes_stored() + p_d.bytes_stored();
    let dbs_4443 = vec![p_a, p_b, p_c, p_d];

    // Single PDB (just the 4-tile one).
    let h_p4 = PdbHeuristic::new(&dbs_4443[0]);
    benchmark(
        "Single PDB (k=4 tiles 1..4)",
        dbs_4443[0].bytes_stored(),
        &h_p4,
        &samples,
        &truth,
    )
    .print();

    // Additive partition over all 15 tiles.
    let h_add = AdditivePdbHeuristic::new(&dbs_4443);
    benchmark(
        "Additive 4+4+4+3 (covers all 15)",
        bytes_4443,
        &h_add,
        &samples,
        &truth,
    )
    .print();

    // Korf-style max(additive, reflected).
    let h_refl_inner = AdditivePdbHeuristic::new(&dbs_4443);
    let h_refl = ReflectedHeuristic::new(h_refl_inner);
    let h_korf = MaxHeuristic::new(&h_add as &dyn Heuristic, &h_refl as &dyn Heuristic);
    benchmark(
        "Max(additive 4+4+4+3, reflected)",
        bytes_4443,
        &h_korf,
        &samples,
        &truth,
    )
    .print();

    println!(
        "\n(Run with feature flags and built P7/P8 PDBs from data/ for the Korf 7-8 partition.)"
    );
}
